<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Hotel::insert([
            [
                'name' => 'Grand Palace Hotel',
                'address1' => '12 Avenue des Lumières',
                'address2' => null,
                'zipcode' => '75001',
                'city' => 'Paris',
                'country' => 'France',
                'lat' => 48.8566130,
                'lng' => 2.3456789,
                'description' => 'Hôtel luxueux au cœur de Paris avec spa et vue sur les monuments.',
                'max_capacity' => 120,
                'price_per_night' => 189.99,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Seaside Resort',
                'address1' => '45 Beach Avenue',
                'address2' => null,
                'zipcode' => '06000',
                'city' => 'Nice',
                'country' => 'France',
                'lat' => 43.710173,
                'lng' => 7.261953,
                'description' => 'Resort en bord de mer avec piscine et activités nautiques.',
                'max_capacity' => 80,
                'price_per_night' => 150.00,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Mountain Inn',
                'address1' => '10 Alpine Road',
                'address2' => null,
                'zipcode' => '74400',
                'city' => 'Chamonix',
                'country' => 'France',
                'lat' => 45.9237,
                'lng' => 6.8694,
                'description' => 'Petit hôtel confortable au pied des montagnes avec vue sur le Mont Blanc.',
                'max_capacity' => 50,
                'price_per_night' => 120.50,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'City Center Lodge',
                'address1' => '7 Rue du Commerce',
                'address2' => null,
                'zipcode' => '69002',
                'city' => 'Lyon',
                'country' => 'France',
                'lat' => 45.764043,
                'lng' => 4.835659,
                'description' => 'Hôtel moderne au centre-ville, proche des commerces et restaurants.',
                'max_capacity' => 70,
                'price_per_night' => 110.00,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Historic Inn',
                'address1' => '23 Rue Royale',
                'address2' => null,
                'zipcode' => '13001',
                'city' => 'Marseille',
                'country' => 'France',
                'lat' => 43.296482,
                'lng' => 5.36978,
                'description' => 'Hôtel avec charme historique et architecture typique.',
                'max_capacity' => 60,
                'price_per_night' => 99.99,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Lakeside Hotel',
                'address1' => '1 Lake Street',
                'address2' => null,
                'zipcode' => '74000',
                'city' => 'Annecy',
                'country' => 'France',
                'lat' => 45.899247,
                'lng' => 6.129384,
                'description' => 'Hôtel avec vue sur le lac et activités nautiques.',
                'max_capacity' => 55,
                'price_per_night' => 130.00,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Countryside Retreat',
                'address1' => '15 Route de Campagne',
                'address2' => null,
                'zipcode' => '16100',
                'city' => 'Cognac',
                'country' => 'France',
                'lat' => 45.6980,
                'lng' => 0.3297,
                'description' => 'Retraite calme à la campagne, idéal pour se détendre.',
                'max_capacity' => 40,
                'price_per_night' => 95.50,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Airport Hotel',
                'address1' => '8 Avenue des Aéroports',
                'address2' => null,
                'zipcode' => '31000',
                'city' => 'Toulouse',
                'country' => 'France',
                'lat' => 43.604652,
                'lng' => 1.444209,
                'description' => 'Hôtel pratique proche de l’aéroport, parfait pour escales.',
                'max_capacity' => 100,
                'price_per_night' => 89.99,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Boutique Stay',
                'address1' => '5 Rue des Arts',
                'address2' => null,
                'zipcode' => '67000',
                'city' => 'Strasbourg',
                'country' => 'France',
                'lat' => 48.573405,
                'lng' => 7.752111,
                'description' => 'Petit hôtel boutique avec décoration design et moderne.',
                'max_capacity' => 30,
                'price_per_night' => 140.00,
                'created_at' => now (),
                'updated_at' => now (),
            ],
            [
                'name' => 'Seaview Hotel',
                'address1' => '100 Coastal Road',
                'address2' => null,
                'zipcode' => '34000',
                'city' => 'Montpellier',
                'country' => 'France',
                'lat' => 43.6119,
                'lng' => 3.8772,
                'description' => 'Hôtel avec vue panoramique sur la mer Méditerranée.',
                'max_capacity' => 90,
                'price_per_night' => 175.00,
                'created_at' => now (),
                'updated_at' => now (),
            ],
        ]);
    }
}
